version: '3'

services:

  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_USER: travis
      MYSQL_PASSWORD: Password12!
      MYSQL_ROOT_PASSWORD: Password12!
      MYSQL_DATABASE: testdb

  pgdb:
    image: postgres
    environment:
      # Lets use docker-entrypoint-initdb.d/init-user-db.sh
      # To set up user and Privileges
      # POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password12!
      POSTGRES_DB: testdb

  retrieverj:
    container_name: rej_image
    # We can run the Dockerfile to create the image tagged retj
    # And remove the build ., but we keep this line for  
    # future debugging
    image: retj
    command: bash -c "python --version"
    environment:
      # If on_travis is set, use service names as hosts(travis)
      # Otherwise use localhost (local tests)
      "TRAVIS_OR_DOCKER" : "true"
    build: . 
    depends_on:
      - mysqldb
      - pgdb
    ports:
      - 5001:80
